@startuml manage_parking_current_info

left to right direction
skinparam packageStyle rect

actor "Chủ bãi đỗ" as ParkingOwner
actor "Nhân viên bãi đỗ" as ParkingEmployee

rectangle "Quản lý thông tin hiện tại của bãi đỗ" as ManageParkingCurrentInfo {
  'ParkingOwner'
    ParkingOwner -- (Xem thông tin hiện tại của bãi đỗ)
    ParkingOwner -- (Xem danh sách nhân viên đang làm việc)
    ParkingOwner -- (Xem thông tin xe đỗ và thông tin vé)
    ParkingOwner -- (Xem các thông tin phân tích tình trạng bãi đỗ)
  'ParkingEmployee'
    (Xem thông tin hiện tại của bãi đỗ) -- ParkingEmployee
    (Xem thông tin xe đỗ và thông tin vé) -- ParkingEmployee
}

@enduml