@startuml manage_account_infor

left to right direction
skinparam packageStyle rect

actor "Chủ phương tiện" as VehicleOwner

rectangle "Quản lý thông tin tài khoản" as ManageAccountInfor {
  'VehicleOwner'
    VehicleOwner -- (Xem thông tin tài khoản)
    VehicleOwner -- (Cập nhật thông tin tài khoản)
    VehicleOwner -- (Tìm kiếm bãi đỗ yêu thích)
    VehicleOwner -- (Thêm bãi đỗ yêu thích)
    VehicleOwner -- (Xóa bãi đỗ yêu thích)
}

@enduml
