@startuml receive_notification

left to right direction
skinparam packageStyle rect

actor "Chủ phương tiện" as VehicleOwner
actor "Chủ bãi đỗ" as ParkingOwner
actor "Nhân viên bãi đố" as ParkingStaff

rectangle "Nhận thông báo" as ReceiveNotification {
  'VehicleOwner'
  (Nhận thông báo) -- VehicleOwner
  'ParkingOwner'
  (Nhận thông báo) -- ParkingOwner
  ParkingOwner -- (Gửi thông báo)
  'ParkingStaff'
  (Nhận thông báo) -- ParkingStaff
  ParkingStaff -- (Gửi thông báo)
}

@enduml