@startuml package_detail

skinparam Linetype ortho

package "pkg" {
  package "Controller" {
    class "Account Controller" as AccountController
    class "Parking Controller" as ParkingController
    class "Payment Controller" as PaymentController
    class "Notification Controller" as NotificationController
    class "Feedback Controller" as FeedbackController
    class "Booking Controller" as BookingController
  }

  package "Service" {
    class "Account Service" as AccountService
    class "Parking Service" as ParkingService
    class "Payment Service" as PaymentService
    class "MongoDB Service" as MongoDBService
    class "Booking Service" as BookingService
  }

  package "Repository" {
    class "Account Repository" as AccountRepository
    class "Parking Repository" as ParkingRepository
    class "Payment Repository" as PaymentRepository
    class "Notification Repository" as NotificationRepository
    class "Feedback Repository" as FeedbackRepository
    class "Ticket Repository" as TicketRepository
  }

  package "Model" {
    class "Account" as Account
    class "Parking" as Parking
    class "Payment" as Payment
    class "Notification" as Notification
    class "Feedback" as Feedback
    class "Ticket" as Ticket
  }

  AccountController o-- AccountService
  FeedbackController o-- AccountService
  BookingController o-- AccountService
  NotificationController o-- AccountService
  PaymentController o-- AccountService

  ParkingController o-- ParkingService
  BookingController o-- ParkingService

  PaymentController o-- PaymentService
  BookingController o-- PaymentService

  NotificationController o-- MongoDBService
  FeedbackController o-- MongoDBService
  
  BookingController o-- BookingService
  
  
  

  AccountService o-- AccountRepository
  ParkingService o-- ParkingRepository
  PaymentService o-- PaymentRepository
  MongoDBService o-- NotificationRepository
  MongoDBService o-- FeedbackRepository
  BookingService o-- TicketRepository

  AccountRepository *-- Account
  ParkingRepository *-- Parking
  PaymentRepository *-- Payment
  NotificationRepository *-- Notification
  FeedbackRepository *-- Feedback
  TicketRepository *-- Ticket
}

@enduml